Django_Project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name="profile"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name="password_reset"),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name="password_reset_done"),
    path('password-reset-CONFIRM/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name="password_reset_confirm"),
    path('', include('blog.urls')),
    path('', include('friend.urls',namespace='friend')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserPostListView, likeview,PostLikeList
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='blog-about'),
    path('like/<int:pk>/', views.likeview, name='likes'),
    # path('post/<int:pk>/postlikes/', views.post_likes, name='post-likes'),
    path('post/<int:pk>/postlikes/', PostLikeList.as_view(), name='post-likes'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    likes = models.ManyToManyField(User, related_name='likes')

    @property
    def number_of_comments(self):
        return BlogComment.objects.filter(blogpost_connected=self).count()

    def total_likes(self):
        return self.likes.count()
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})


class BlogComment(models.Model):
    blogpost_connected = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(blank=True)
    date_posted = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return str(self.author) + ',' + self.blogpost_connected.title[:40]

blog/forms.py
from django import forms
from .models import BlogComment

class NewCommentForm(forms.ModelForm):
    class Meta:
        model = BlogComment
        fields = ('content',)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, BlogComment
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import NewCommentForm

def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context)

class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']         #to show most recent post
    paginate_by = 6
    
    # def get_context_data(self, *args, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     data = get_object_or_404(Post, id=self.kwargs['pk'])
    #     total_likes = data.total_likes()
    #     context["total_likes"] = total_likes
    #     return context
   
        
class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']         #to show most recent post
    paginate_by = 6

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')



class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        data = get_object_or_404(Post, id=self.kwargs['pk'])
        liked=False
        if data.likes.filter(id=self.request.user.id).exists():
            liked=True
        comments_connected = BlogComment.objects.filter(blogpost_connected=self.get_object()).order_by('-date_posted')
        context['comments'] = comments_connected
        if self.request.user.is_authenticated:
            context['comment_form'] = NewCommentForm(instance=self.request.user)
        total_likes = data.total_likes()
        context["total_likes"] = total_likes
        context["post_is_liked"] = liked
        return context

    def post(self, request, *args, **kwargs):
        new_comment = BlogComment(content=request.POST.get('content'),
                                  author=self.request.user,
                                  blogpost_connected=self.get_object())
        new_comment.save()
        return self.get(self, request, *args, **kwargs)

class PostLikeList(DetailView):
    model = Post
    template_name = 'blog/post_likes.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        posts = get_object_or_404(Post, id=self.kwargs['pk'])
        post_likes = posts.likes.all()
        context = {'post_likes': post_likes}
        return context







class PostCreateView(LoginRequiredMixin,CreateView):
    model = Post
    fields = ['title', 'content', 'image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin,CreateView):
    model = Post
    fields = ['title', 'content', 'image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin,DeleteView):
    model = Post
    success_url = "/"
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})

def likeview(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)

    return HttpResponseRedirect(reverse('post-detail', args=[str(pk)]))



# def post_likes(request, pk):
#     posts = get_object_or_404(Post, pk=pk)
#     post_likes = posts.likes.all()
#     data = Post.objects.all().filter(pk=pk)
#     context = {'post_likes': post_likes,
#                 'post': data,
#                 }
#     return render(request, 'blog/post_likes.html', context)

blog/templates/blog/about.html
 
{% extends "blog/base.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

    {% if title %}
        <title>Blog - {{ title }}</title>
    {% else %}
        <title>Blog</title>
    {% endif %}
</head>
<body style="position:relative; min-height:100%;">
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'post-create' %}">New Post</a>
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                  <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% if messages %}
              {% for message in messages %}
               <div class="alert alert-{{ message.tags }}">
                 {{ message }}
               </div>
              {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
          </div>
          <div class="col-md-4">
            <div class="content-section">
              <h3>Ouick Links</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Official Website</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p>
            </div>
          </div>
        </div>
      </main>

      
            <!-- Footer -->
        <footer class="footer-fix font-small footer-bg-color pt-4 " style="background-color: #3e4551; bottom:0; position: relative; top:38vh; width:100%; height: 19vh;">

          <!-- Footer Links -->
          <div class="container text-center text-md-left">

            <!-- Grid row -->
            <div class="row">

              <!-- Grid column -->
              <div class="mx-auto">

                <!-- Content -->
                <h5 class="font-weight-bold text-uppercase mt-2 mb-2" style="color:#fff">All latest news official and unofficial</h5>
                <p></p>

              </div>
              <!-- Grid column -->

              <hr class="clearfix w-100 d-md-none">

            

            </div>
            <!-- Grid row -->

          </div>
          <!-- Footer Links -->

          <!-- Call to action -->
          <ul class="list-unstyled list-inline text-center py-2">
            <li class="list-inline-item">
              <h5 class="mb-3" style="color:#fff">Register for free</h5>
            </li>
            <li class="list-inline-item">
              <a href="{% url 'register' %}" class="btn btn-danger btn-rounded">Sign up!</a>
            </li>
          </ul>
          <!-- Call to action -->

          

          
          <div class="footer-copyright text-center py-3 footer-color" style="background-color: rgba(0,0,0,0.2); color:#fff">© 2020 Copyright:
            <a href="https://www.linkedin.com/in/rahulgoy/"> Rahul Goyal</a>
          </div>
          

        </footer>
      

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

blog/templates/blog/blogpost-like.html
{% extends "blog/base.html" %}
{% block content %}



{% endblock %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
<html>
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src = "{{ post.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
              </div>
            <div>
              <h2><a class="article-title" href="{%url 'post-detail' post.id %}">{{ post.title }}</a></h2>
              <p class="article-content">{{ post.content }}</p>
              {% if post.image %}
                <img class="img-responsive imgset" src="{{ post.image.url }}" style="height:350px; width: 500px; max-width: 100%; height: auto;"/>
              {% endif %}
              
              <form action="{% url 'likes' post.pk %}" method="POST">
                {% csrf_token %}
                <button type="submit", name="post_id", value="{{ post.id }}", class="btn btn-primary btn-sm">Like</button>
                
              </form> 


            </div>
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}
        {% if page_obj.has_previous %}
          <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
          {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
          {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
          {% endif %}
        {% endfor %}
    
        {% if page_obj.has_next %}
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}

    </html>
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
 
{% extends "blog/base.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
        
    </div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}
<html>
  <style>
    .form-group label{
      
      display: none;
    }
    #id_content{
      width:25vw;
      height:5vh;
      
    }
  </style>

        <article class="media content-section">
          <img class="rounded-circle article-img" src = "{{ object.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-posts' object.author.username %}">{{ object.author }}</a>
              <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>

              {% if object.author == user %}
                  <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' object.id %}">Update</a>
                    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' object.id %}">Delete</a>
                  </div>
              {% endif %}
            </div>
            <h2 class="article-title">{{ object.title }}</h2>
            <p class="article-content">{{ object.content }}</p>
            {% if object.image %}
              <img class="img-responsive" src="{{ object.image.url }}" style="height:250px; width: 500px; max-width: 100%; height: auto;"/>
            {% endif %}
            <br>
            <form action="{% url 'likes' post.pk %}" method="POST">
              {% csrf_token %}
              {% if post_is_liked %}
              <button type="submit", name="post_id", value="{{ post.id }}", class="btn btn-primary btn-sm">Unike</button>
              {% else %}
              <button type="submit", name="post_id", value="{{ post.id }}", class="btn btn-primary btn-sm">Like</button>
              {% endif %}
              <a href="{% url 'post-likes' post.id %}">{{ total_likes }}-Likes</a>
            </form> 
                <br>
            <!-- COMMENTS  -->
              
              <div id="comments_section">

                {% if user.is_authenticated %}
                <form method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    {{ comment_form }}
                    <button class="btn btn-info" type="submit">Add comment <i class="fas fa-comments"></i></button>
                  </div>
                </form>
                {% else %}
                <a class="btn btn-outline-info" href="{% url 'login' %}?next={{request.path}}">Log in to add a comment!</a><br>
                {% endif %}

                {% if comments %}
                <strong class="text-secondary">{{ object.number_of_comments }} Comment{{ object.number_of_comments|pluralize }}</strong>
                <hr>
                <ul>
                  {% for comment in comments %}
                  <li>           
                  <div>
                      <span>
                        <strong class="text-info">{{ comment.author }} </strong>
                        <small class="text-muted">{{ comment.date_posted }}</small>
                      </span>
                      <p>
                        {{ comment.content|safe }}
                      </p>
                    </div>
                  </li>
                  {% endfor %}
                </ul>
                {% else %}
                  <strong class="text-secondary">No comments yet...</strong>
                {% endif %}

              </div>



          </div>
        </article>
        </html>
{% endblock content %}

blog/templates/blog/post_form.html
 
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
        
    </div>
{% endblock content %}

blog/templates/blog/post_likes.html
{% extends "blog/base.html" %}
{% block content %}
<html>
    <article class="media content-section">
        <img class="rounded-circle article-img" src = "{{ object.author.profile.image.url }}">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{% url 'user-posts' object.author.username %}">{{ object.author }}</a>
            <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>

            {% if object.author == user %}
                <div>
                  <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' object.id %}">Update</a>
                  <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' object.id %}">Delete</a>
                </div>
            {% endif %}
          </div>
          <h2 class="article-title">{{ object.title }}</h2>
          <p class="article-content">{{ object.content }}</p>
          {% if object.image %}
            <img class="img-responsive" src="{{ object.image.url }}" style="height:250px; width: 500px; max-width: 100%; height: auto;"/>
          {% endif %}
          <br>
          
      
            {% for post in post_likes %}
                {{ post.username }}
            {% endfor %}
                
        </div>
    </article>
    </html>
{% endblock content %}

blog/templates/blog/user_posts.html
{% extends "blog/base.html" %}
{% block content %}

<div class="content-section">
  <div class="media">
    {% for post in posts|slice:":1" %}
      <img class="rounded-circle account-img" src="{{ post.author.profile.image.url }}">
      {% endfor %}
      <div class="media-body">
          <h2 class="account-heading">{{ view.kwargs.username }}</h2>
      </div>
      
  </div>
  </div>

    <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in posts %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src = "{{ post.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{%url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
            {% if post.image %}
            <img class="img-responsive imgset" src="{{ post.image.url }}" style="height:350px; width: 500px; max-width: 100%; height: auto;"/>
            {% endif %}



            
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}
        {% if page_obj.has_previous %}
          <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
          {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
          {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
          {% endif %}
        {% endfor %}
    
        {% if page_obj.has_next %}
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}
{% endblock content %}